config/routes.rb
AdNetwork::Application.routes.draw do
  match "/" => 'application#index'
  match "/login" => 'application#login'
  match "/logout" => 'application#logout'

  match "/click" => 'advertising#click'
  match "/get_ads(.:format)" => 'advertising#get_ads'
  match "/get_ads_detail" => 'advertising#get_ads_detail'
  match "/test_app" => 'advertising#test_app'
  match "/advertising/bring_all_ads_to_view" => 'advertising#bring_all_ads_to_view'

  resources :campaigns do
    resources :ads
  end

  match ':controller(/:action(/:id(.:format)))'
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  STATUS_STARTED, STATUS_STOPPED, STATUS_TMP_STOPPED = 0, 1, 2

  belongs_to :member
  has_many :ads

  validates_presence_of :name

  attr_accessor :ctr, :clicks, :views, :expenses

  attr_protected :balance

  def fresh_ads
    self.ads.sort {|a,b| b.created_at <=> a.created_at }
  end

  def calculate_statistics
      self.clicks = 0
      self.views = 0
      self.expenses = 0
      self.ads.each do |a|
        self.clicks = self.clicks + a.clicks
        self.views = self.views + a.views
        self.expenses = self.expenses + a.expenses
      end
      self.ctr = 1.0 * self.clicks / self.views if self.views != 0
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  layout "advertiser_webmaster"
  before_filter :check_login
  before_filter :init_advertiser

  def index
    @campaigns = Campaign.where(["member_id = ?", session[:member_id]]).order("created_at DESC")
    @campaigns.each do |c|
      c.calculate_statistics
    end
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new params[:campaign]
    @campaign.member_id = session[:member_id]
    if @campaign.save
      flash.now[:notice_msg] = "Кампания создана. Добавьте в нее объявления."
      index
      render "index"
    else
      flash.now[:error_msg] = "Укажите название кампании."
      render "new"
    end
  end

  def show
    @campaign = @campaign || Campaign.find(params[:id])
    @campaign_name = @campaign_name || @campaign.name
    if (@campaign.member_id != session[:member_id])
      redirect_to campaigns_url
    end
    @campaign.calculate_statistics
  end

  def update
    @campaign = Campaign.find(params[:id])
    @campaign_name = @campaign.name
    if (@campaign.member_id != session[:member_id])
      redirect_to campaigns_url
    end
    if @campaign.update_attributes params[:campaign]
      flash.now[:notice_msg] = "Изменения сохранены."
      @campaign_name = @campaign.name
      show
      render "show"
    else
      flash.now[:error_msg] = "Изменения не сохранены."
      show
      render "show"      
    end
  end

  private

  def init_advertiser
    @balance = session[:member_balance]
    @webmaster = false
  end

end

app/helpers/campaigns_helper.rb
module CampaignsHelper

  def select_campaign_status f, status
    if (status == Campaign::STATUS_TMP_STOPPED)
      f.select :status,
               [["Приостановлена", Campaign::STATUS_TMP_STOPPED]],
               {},
               {:class => "BigInput", :disabled => true}
    else
      f.select :status,
               [["Запущена", Campaign::STATUS_STARTED], ["Остановлена", Campaign::STATUS_STOPPED]],
               {},
               {:class => "BigInput", :length => 30}
    end
  end

  def campaign_status status
    if (status == Campaign::STATUS_STARTED)
      return "Запущена"
    else
      if status == Campaign::STATUS_STOPPED
        return "Остановлена"
      end
    end
    "Приостановлена"  
  end

end

app/views/campaigns/_menu.html.erb
<div id="Menu">
  <div>
    <div class="Entered">
        <p><%= link_to_unless(["campaigns", "ads"].any? {|e| e == controller_name}, "Рекламные кампании", campaigns_path)  %></p>
    </div>
    <div>
        <p><%= link_to_unless "ads_statistics" == controller_name , "Статистика", "STATS LINK"  %></p>
    </div>
  </div>
</div>

app/views/campaigns/_messages.html.erb
  <% if flash.now[:error_msg] %>
    <div class="ErrorMessage" id="error_message_static">
      <div>
        <p><%= flash.now[:error_msg] %></p>
      </div>
    </div>
  <% end %>
  <% if flash.now[:notice_msg] %>
    <div class="NoticeMessage" id="notice_message_static">
      <div>
        <p><%= flash.now[:notice_msg] %></p>
      </div>
    </div>
  <% end %>
    <div class="ErrorMessage" id="error_message">
      <div>
        <p></p>
      </div>
    </div>
    <div class="NoticeMessage" id="notice_message">
      <div>
        <p></p>
      </div>
    </div>

app/views/campaigns/index.html.erb
<%= render :partial => "menu" %>

<div class="Container">
  
    <%= render :partial => "messages" %>


    <div class="ListHeader">
      <div class="Col1">
        <div>
            <p>Кампания</p>
        </div>
      </div>
      <div class="Col245">
        <div>
            <p>Статус</p>
        </div>
      </div>
      <div class="Col3">
        <div>
          <table>
            <tbody>
                <tr>
                  <td colspan="3"><p>Статистика за сегодня</p></td>
                </tr>
                <tr>
                  <td width="100"><p>Показы</p></td>
                  <td width="100"><p>Переходы</p></td>
                  <td width="100"><p>CTR</p></td>
                </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="Col245">
        <div>
            <p>Расход</p>
        </div>
      </div>
      <div class="Col245">
        <div>
            <p>Балланс</p>
        </div>
      </div>
    </div>

    <div class="ListRowEnd">
      
    </div>

    <% @campaigns.each do |campaign| %>

    <div class="ListRow">
      <div class="LCol1">
        <div>
          <p><%= link_to campaign.name, campaign_path(campaign.id) %></p>
        </div>
      </div>
      <div class="LCol24">
        <div>
          <p><%= campaign_status campaign.status %></p>
        </div>
      </div>
      <div class="LCol3_part">
        <div>
          <p><%= campaign.views %></p>
        </div>
      </div>
      <div class="LCol3_part">
        <div>
          <p><%= campaign.clicks %></p>
        </div>
      </div>
      <div class="LCol3_part">
        <div>
          <p><%= ctr_percent(campaign.ctr) if campaign.ctr %></p>
        </div>
      </div>
      <div class="LCol24">
        <div>
          <p><%= campaign.expenses %></p>
        </div>
      </div>
      <div class="LCol5">
        <div>
          <p><%= campaign.balance %></p>
        </div>
      </div>
    </div>

    <% end %>

    <div class="ListRowEnd">

    </div>

    <div class="CreateCampaign">
      <div>
        <p><%= link_to "Создать кампанию и привлечь посетителей на сайт", new_campaign_path %></p>
      </div>
    </div>
</div>

app/views/campaigns/new.html.erb
<%= render :partial => "menu" %>

<div class="Container">
    <%= render :partial => "messages"%>
    <div>
      <%= form_for @campaign, :url => campaigns_path, :html => {:class => "CreateCampaignForm"} do |f| %>
      <table class="CreateCampaign">
        <tr>
          <td class="Left"><%= f.label :name, "Название кампании", :class => "BigInput" %></td>
          <td><%= f.text_field :name, :class => "BigInput" %></td>
        </tr>
        <tr>
          <td></td>
          <td><%= f.submit "Создать", :class => "BigInputButton" %></td>
        </tr>
      </table>
      <% end  %>
    </div>
</div>

app/views/campaigns/show.html.erb
<%= render :partial => "campaigns/menu" %>

<!--<div id="DecreaseBudgetBox">-->
   <!--fgfdg-->
<!--</div>-->

<span id="campaign_id" style="display:none;"><%= @campaign.id %></span>


<div class="Container">
  
    <%= render :partial => "campaigns/messages" %>

    <div class="Path">
      <div class="Element">
        <div>
          <p><%= link_to "Рекламные кампании", campaigns_path, :class => "Big" %></p>
        </div>
      </div>
      <div class="Separator">
        <div>
          <img src="/images/PathSeparator.png" />
        </div>
      </div>
      <div class="Element">
        <div>
          <p><%= @campaign_name %></p>
        </div>
      </div>
      <div class="BalanceContainer">
        <div>
          <p>Баланс: <span id="campaign_balance"><%= @campaign.balance %></span> руб.&nbsp;</p>
          <a href="#" id="budget_increase"><img src="/images/Increase.png" alt="Увеличить"></a>
          <a href="#" id="budget_decrease"><img href="#" src="/images/Decrease.png" alt="Уменьшить"></a>
        </div>
      </div>
    </div>

    <div class="CampaignInfo">
      <div class="StatisticsHeader">
        <p>Статистика кампании за сегодня:</p>
      </div>
      <div class="LeftColumn">
        <div>
            <%= form_for @campaign, campaigns_path, :method => "put" do |f| %>
            <table>
              <tbody>
                <tr>
                  <td width="40%"><%= f.label :status, "Статус:", :class =>"BigInput" %></td>
                  <td width="60%"><%= select_campaign_status f, @campaign.status %></td>
                </tr>
                <tr>
                  <td width="40%"><%= f.label :name, "Название:", :class =>"BigInput" %></td>
                  <td width="60%"><%= f.text_area :name, :class => "BigInput", :cols => 23, :rows => 4 %></td>
                </tr>
                <tr>
                  <td width="40%"><%= f.label :limit, "Лимит:", :class =>"BigInput" %></td>
                  <td width="60%"><%= f.text_field :limit, :class => "BigInput", :disabled => true, :size => 15 %></td>
                </tr>
                <tr>
                  <td width="40%"><%= f.label :day_limit, "Дневной лимит:", :class =>"BigInput" %></td>
                  <td width="60%"><%= f.text_field :day_limit, :class => "BigInput", :disabled => true, :size => 15 %></td>
                </tr>
                 <tr>
                  <td width="40%"></td>
                  <td width="60%"><a class="GreenButton" href="#" id="UpdateCampaignButton"><span>Сохранить</span></a></td>
                </tr>
              </tbody>
            </table>
            <% end %>
        </div>
      </div>
      <div class="RightColumn">
        <div>
            <table>
              <tbody>
                <tr>
                  <td width="40%"><p>Показы</p></td>
                  <td width="60%"><p><%= @campaign.views %></p></td>
                </tr>
                <tr>
                  <td width="40%"><p>Переходы</p></td>
                  <td width="60%"><p><%= @campaign.clicks  %></p></td>
                </tr>
                <tr>
                  <td width="40%"><p>Расход</p></td>
                  <td width="60%"><p><%= @campaign.expenses  %> руб.</p></td>
                </tr>
                <tr>
                  <td width="40%"><p>CTR</p></td>
                  <td width="60%"><p><%= ctr_percent(@campaign.ctr) if @campaign.ctr %></p></td>
                </tr>
              </tbody>
            </table>
        </div>
      </div>
    </div>

    <!-- Begin Ads List -->

    <div class="AdListHeader">
      <div class="Col1">
        <div>
            <p>Объявление</p>
        </div>
      </div>
      <div class="Col245">
        <div>
            <p>Статус</p>
        </div>
      </div>
      <div class="Col3">
        <div>
          <table>
            <tbody>
                <tr>
                  <td colspan="3"><p>Статистика за сегодня</p></td>
                </tr>
                <tr>
                  <td width="100"><p>Показы</p></td>
                  <td width="100"><p>Переходы</p></td>
                  <td width="100"><p>CTR</p></td>
                </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="Col245">
        <div>
            <p>Расход</p>
        </div>
      </div>
      <div class="Col245">
        <div>
            <p>Тип</p>
        </div>
      </div>
    </div>

    <div class="ListRowEnd">

    </div>

    <% @campaign.fresh_ads.each do |ad| %>

    <div class="ListRow">
      <div class="LCol1">
        <div>
          <p><%= link_to ad.name, campaign_ad_path(@campaign.id, ad.id) %></p>
        </div>
      </div>
      <div class="LCol24">
        <div>
          <p><%= ad_status ad.status %></p>
        </div>
      </div>
      <div class="LCol3_part">
        <div>
          <p><%= ad.views %></p>
        </div>
      </div>
      <div class="LCol3_part">
        <div>
          <p><%= ad.clicks %></p>
        </div>
      </div>
      <div class="LCol3_part">
        <div>
          <p><%= ctr_percent(1.0 * ad.clicks / ad.views) if ad.views != 0 %></p>
        </div>
      </div>
      <div class="LCol24">
        <div>
          <p><%= ad.expenses %></p>
        </div>
      </div>
      <div class="LCol5">
        <div>
          <p><%= ad_type(ad.ad_type) %></p>
        </div>
      </div>
    </div>

    <% end %>

    <div class="ListRowEnd">

    </div>

    <div class="CreateAd">
      <div>
        <p><%= link_to "Создать объявление", new_campaign_ad_path(@campaign.id) %></p>
      </div>
    </div>
    <!--<textarea rows="5" cols="30" class="BigInput"></textarea>-->
</div>